production:
    type: deploy
    script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include "*.html,*.js,*.png,*.svg,*.jpg,*.jpeg,*.eot,*.ttf,*.woff,*.woff2,*.css,*.css.map,*.ico"
    only:
    - tags
